<?php

namespace Ars\RefTrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * refUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefCodeRepository extends EntityRepository
{
}
