<?php

namespace Ars\RefTrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RefHitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefHitRepository extends EntityRepository
{
}
