services:
    ars_ref_tracker.request_listener:
        class: Ars\RefTrackerBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}
        arguments: [%ars_ref_tracker.query_param_name%, %ars_ref_tracker.cookie_name%, %ars_ref_tracker.cookie_ttl%]
        calls:
            - [setEm, [@doctrine.orm.entity_manager]]
            - [setRouter, [@router]]

    ars_ref_tracker.user_events_listener:
        class: Ars\RefTrackerBundle\EventListener\UserEventsListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: [%ars_ref_tracker.cookie_name%]
        calls:
            - [setEm, [@doctrine.orm.entity_manager]]
            - [setUniqIdGenerator, [@ars_ref_tracker.uniq_id_generator]]

    ars_ref_tracker.uniq_id_generator:
        class: Ars\RefTrackerBundle\Services\UniqIdGenerator
